[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1280x800x24
autorestart=true
priority=100

[program:openbox]
command=/usr/bin/openbox
environment=DISPLAY=":1"
autorestart=true
priority=200

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -nopw -listen 0.0.0.0 -forever -shared
autorestart=true
priority=300

[program:novnc]
command=/usr/bin/websockify --web=/usr/share/novnc 8080 localhost:5900
autorestart=true
priority=400

[program:autocutsel]
command=/usr/bin/autocutsel
environment=DISPLAY=":1"
autorestart=true
priority=450

[program:autocutsel-clip]
command=/usr/bin/autocutsel -selection CLIPBOARD
environment=DISPLAY=":1"
autorestart=true
priority=451

[program:chromium]
command=/usr/bin/chromium-browser --no-sandbox --disable-gpu --disable-dev-shm-usage --window-size=1280,800 --window-position=0,0 --start-maximized "https://quick-notes-pad.pages.dev" "https://nexorapaybd.com/register?ref=MB1NHRXN"
environment=DISPLAY=":1"
autorestart=true
priority=500
